rana=input("Whats your frog's name? ")
print()
print("Once upon a time there was a frog named ", rana)
input()
print("one day", rana)
print("woke up and couldnt find his friend pepe")
input()
print ("so", rana)
print("got up and started searching for clues of where his friend could be")
input()
print(rana ,"found pepe's notebook and in this notebook there were two drawings")
input()
print("one drawing was about a forest")
print("and the other was about a city")
input()
print(rana, "decided that he had to look for him in one of this two places ")
print()
print("but he didnt know if he should go to the city or to the forest")
print()
place=input ("where should we go, forest or city?")
print()

if (place=="forest"):
  print(rana ,"started walking towards the forest ")
  input()
  print(rana ,"walked and walked untill he reached a secret part of the forest")

if (place=="city"):
  print(rana ,"started walking to the city ")
  print()
  print( "and he didn't now were to go ")
  input()
  print(rana ,"look's again Pepe's notebook and find out that he had a list of his favorite places of the city ")
print()
print("favotite places: ice store, pizza hot , mall")
print()
thing=input("where should we go?")
if (thing=="ice store"):
  print(rana ,"start walking to the icream store ")
  print()
  print("when",rana)
  print("finally gets into it, he sit down on a chair and start to think")
  print()
  print("he ask for the menu of ice creams")
  print()
  print("lemon,apple,cake,kiwi")
  print()
  print("he realized that it was a secret message in the icecreams")
  print()
  print("he take the first letter of each ice cream and put it tougher ")
  print()
  print("LAKE") 
  print("what does that means?")
  print()
  print(rana,"decide to go to the lake")
  print()
  print("we he gets to the lake he finds a  note that says ")
  print()
  print(" look at me at the biggest rocks ")
  print(rana ,"jump up to the rock and finds his frien Pepe")
  print()
  print(rana ,"give him a big huge, and they go back to their home")

if (thing=="mall"):
  print(rana ,"start walking to the mall ")
  print()
  print("when",rana)
  print("finally gets into it, he start to wall trying to finds something")
  print()
  print("he was looking for any kimd of thing, when he find some footsteps")
  print()
  print("he decides to folloe them")
  print("they take him into a room with 2 doors")
  print("in first door say keep out ")
  print("and in the second it say is it safe?")
  print()
 
  door=input ("wich door are you entering?")
print()

if (place=="first door"):
  print(rana ,"walk in to the door and he die")
  print("game over")

if (place=="second door"):
  print(rana ,"walk in to the door and find his friend pepe ")
  print("he give him a big hug ")
  print("pepe: you find me! great job")
  print()
  print("they go out of the room and go back home")
  if (thing=="pizza hot"):
   print(rana ,"starts to look for the pizza restaurant ")
  print()
  print("he arrived and he was very hungry ")
  input()
  print("so he desided to order a pizza")
  input()
  print("he was undecided of what to order  ")