nombre=input('¿Cómo te llamas?:  ')
print('un gusto',nombre)
Comida=input('¿Cuál es tu comida favorita: ')
print('Que delicioso')
Pais=input('¿En que pais vives?: ')
print('que bonito pais es',Pais)
Serie=input('¿Cuál es tu serie favorita?: ')
print('la vere algun día')
Edad=input('¿Qué edad tienes?: ')
print('¡increible!')
Deporte=input('¿Cuál es tu deporte favorito?: ')
print('es muy divertido')
Pizza=input('¿te gusta la pizza?: ')
print('Es deliciosa')
Materia=input('¿Cuàl es tu materia favorita?: ')
print('la mia es Español')
PG=input('Perros o gatos???: ')
print('A mi me gustan los dos')
HM=input('¿Eres Hombre o Mujer?: ')
print('Gracias por contestar este cuestionario ')